#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/config.sh"

# ─── Help ────────────────────────────────────────────────────────────────────
usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Interactive wizard to configure MustangClaw.

Creates ~/.mustangclaw/config.env with your settings. All values have
sensible defaults — just press Enter to accept them.

Options:
  --reset   Overwrite existing config without prompting
  --help    Show this help message
EOF
    exit 0
}

# ─── Parse flags ─────────────────────────────────────────────────────────────
RESET=false
for arg in "$@"; do
    case "$arg" in
        --reset)   RESET=true ;;
        --help|-h) usage ;;
        *) log_error "Unknown option: $arg"; usage ;;
    esac
done

# ─── Helpers ─────────────────────────────────────────────────────────────────
CONFIG_FILE="$MUSTANGCLAW_CONFIG_DIR/config.env"

# Prompt with a default value.  Usage: ask VAR "Prompt text" "default"
ask() {
    local var="$1" prompt="$2" default="$3"
    local value
    printf "${_CYAN}%s${_NC} [%s]: " "$prompt" "$default"
    read -r value
    value="${value:-$default}"
    printf -v "$var" '%s' "$value"
}

# Prompt yes/no.  Usage: ask_yn VAR "Prompt text" "y" or "n"
ask_yn() {
    local var="$1" prompt="$2" default="$3"
    local hint="y/N"
    [[ "$default" == "y" ]] && hint="Y/n"
    local answer
    printf "${_CYAN}%s${_NC} [%s]: " "$prompt" "$hint"
    read -r answer
    answer="${answer:-$default}"
    case "$answer" in
        [yY]|[yY][eE][sS]) printf -v "$var" '%s' "true" ;;
        *) printf -v "$var" '%s' "false" ;;
    esac
}

# Prompt for a secret (no echo).  Usage: ask_secret VAR "Prompt text"
ask_secret() {
    local var="$1" prompt="$2"
    local value
    printf "${_CYAN}%s${_NC}: " "$prompt"
    read -rs value
    echo ""
    printf -v "$var" '%s' "$value"
}

# ─── Pre-flight ──────────────────────────────────────────────────────────────
echo ""
printf "${_GREEN}MustangClaw Setup Wizard${_NC}\n"
echo "─────────────────────────────────────"
echo "This will create $CONFIG_FILE"
echo "Press Enter to accept the default shown in brackets."
echo ""

if [[ -f "$CONFIG_FILE" && "$RESET" != "true" ]]; then
    log_warn "Config already exists at $CONFIG_FILE"
    if ! confirm "Overwrite it?"; then
        log_info "Aborted. Run with --reset to skip this prompt."
        exit 0
    fi
    echo ""
fi

# ─── Create directories ─────────────────────────────────────────────────────
mkdir -p "$MUSTANGCLAW_CONFIG_DIR"
chmod 700 "$MUSTANGCLAW_CONFIG_DIR"
mkdir -p "$MUSTANGCLAW_WORKSPACE_DIR"
chmod 700 "$MUSTANGCLAW_WORKSPACE_DIR"

# ─── Section: Ports ─────────────────────────────────────────────────────────
printf "${_GREEN}── Ports ──${_NC}\n"
ask _GATEWAY_PORT   "Gateway port"   "$GATEWAY_PORT"
ask _BRIDGE_PORT    "Bridge port"    "$BRIDGE_PORT"
ask _POSEIDON_PORT  "Poseidon port"  "$POSEIDON_PORT"
echo ""

# ─── Section: DigitalOcean ──────────────────────────────────────────────────
printf "${_GREEN}── DigitalOcean ──${_NC}\n"
ask_yn _DO_ENABLED "Configure DigitalOcean deployment?" "n"

_DO_TOKEN=""
_DO_DROPLET=""
_DO_REGION=""
_DO_SIZE=""
_DO_SSH_FP=""

if [[ "$_DO_ENABLED" == "true" ]]; then
    ask_secret _DO_TOKEN  "  API token (dop_v1_...)"
    ask _DO_DROPLET       "  Droplet name"    "$DO_DROPLET_NAME"
    ask _DO_REGION        "  Region"           "$DO_REGION"
    ask _DO_SIZE          "  Droplet size"     "$DO_SIZE"
    ask _DO_SSH_FP        "  SSH key fingerprint (blank = auto-detect)" ""
fi
echo ""

# ─── Section: Tailscale ──────────────────────────────────────────────────────
_TS_ENABLED="false"
_TS_AUTH_KEY=""
_TS_MODE=""

if [[ "$_DO_ENABLED" == "true" ]]; then
    printf "${_GREEN}── Tailscale ──${_NC}\n"
    ask_yn _TS_ENABLED "Enable Tailscale for remote access?" "n"

    if [[ "$_TS_ENABLED" == "true" ]]; then
        ask_secret _TS_AUTH_KEY "  Auth key (tskey-auth-...)"
        ask _TS_MODE            "  Mode (serve = tailnet-only, funnel = public)" "$TAILSCALE_MODE"
    fi
    echo ""
fi

# ─── Write config ───────────────────────────────────────────────────────────
cat > "$CONFIG_FILE" <<EOF
# MustangClaw configuration — generated by mustangclaw init
# Edit freely; re-run 'mustangclaw init' to regenerate.

# ─── Ports ──────────────────────────────────────────────────────────────────
GATEWAY_PORT=$_GATEWAY_PORT
BRIDGE_PORT=$_BRIDGE_PORT
POSEIDON_PORT=$_POSEIDON_PORT

# ─── DigitalOcean ───────────────────────────────────────────────────────────
EOF

if [[ "$_DO_ENABLED" == "true" ]]; then
    cat >> "$CONFIG_FILE" <<EOF
DIGITALOCEAN_ACCESS_TOKEN="$_DO_TOKEN"
DO_DROPLET_NAME="$_DO_DROPLET"
DO_REGION="$_DO_REGION"
DO_SIZE="$_DO_SIZE"
DO_SSH_KEY_FINGERPRINT="$_DO_SSH_FP"
EOF
else
    cat >> "$CONFIG_FILE" <<EOF
# Uncomment and fill in to enable DigitalOcean deployment:
# DIGITALOCEAN_ACCESS_TOKEN=""
# DO_DROPLET_NAME="mustangclaw-gateway"
# DO_REGION="nyc3"
# DO_SIZE="s-2vcpu-4gb"
# DO_SSH_KEY_FINGERPRINT=""
EOF
fi

# ─── Tailscale ─────────────────────────────────────────────────────────────
if [[ "$_TS_ENABLED" == "true" ]]; then
    cat >> "$CONFIG_FILE" <<EOF

# ─── Tailscale ─────────────────────────────────────────────────────────────
TAILSCALE_ENABLED=true
TAILSCALE_AUTH_KEY="$_TS_AUTH_KEY"
TAILSCALE_MODE="$_TS_MODE"
EOF
fi

chmod 600 "$CONFIG_FILE"

# ─── Write openclaw.json (gateway config) ──────────────────────────────────
OPENCLAW_JSON="$MUSTANGCLAW_CONFIG_DIR/openclaw.json"
if [[ ! -f "$OPENCLAW_JSON" ]]; then
    cat > "$OPENCLAW_JSON" <<'JSONEOF'
{
  "gateway": {
    "mode": "local"
  }
}
JSONEOF
    chmod 600 "$OPENCLAW_JSON"
    log_info "Created $OPENCLAW_JSON"
fi

# ─── Summary ────────────────────────────────────────────────────────────────
echo "─────────────────────────────────────"
log_info "Config saved to $CONFIG_FILE"
log_info "Directories created:"
log_info "  $MUSTANGCLAW_CONFIG_DIR"
log_info "  $MUSTANGCLAW_WORKSPACE_DIR"
echo ""
log_info "Next steps:"
echo "  mustangclaw build   — clone repo & build Docker image"
echo "  mustangclaw run     — start the gateway locally"
echo "  mustangclaw setup   — configure API keys & providers"
if [[ "$_DO_ENABLED" == "true" ]]; then
    echo "  mustangclaw deploy  — provision a DigitalOcean droplet"
fi
if [[ "$_TS_ENABLED" == "true" ]]; then
    echo ""
    echo "  Tailscale: enabled ($TAILSCALE_MODE mode)"
    echo "  After deploy, Poseidon will be at: https://<droplet>.<tailnet>.ts.net"
fi
